(source melpa)

(depends-on "cider")
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "ido")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "soothe-theme")
(depends-on "undo-tree")
(depends-on "yaml-mode")
(depends-on "yasnippet")