(global-undo-tree-mode)
(rainbow-delimiters-mode)
(global-linum-mode)
(projectile-global-mode)
(electric-indent-mode t)
(ido-mode 1)
(ido-everywhere 1)
(flx-ido-mode 1)
(ido-vertical-mode 1)
;; disable ido faces to see flx highlights.
(setq ido-use-faces nil)
(setq rbenv-installation-dir "~/.rbenv")
(setq js-indent-level 2)
(global-rbenv-mode)
(setq rbenv-show-active-ruby-in-modeline nil)
(set-fringe-mode 0)
(smartparens-global-mode t)
(drag-stuff-mode t)
(define-globalized-minor-mode global-fci-mode fci-mode (lambda () (fci-mode 1)))
(define-globalized-minor-mode global-drag-stuff-mode drag-stuff-mode (lambda () (drag-stuff-mode 1)))
(define-globalized-minor-mode global-wrap-region-mode wrap-region-mode (lambda () (wrap-region-mode 1)))
(global-drag-stuff-mode 1)
(global-wrap-region-mode 1)
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
(show-smartparens-global-mode +1)
(setq sp-autoescape-string-quote nil)
(setq ruby-deep-indent-paren nil)

(global-company-mode t)
(push 'company-robe company-backends)

(region-bindings-mode t)
(region-bindings-mode-enable)

(setq sml/theme 'dark)
(sml/setup)
(setq ruby-insert-encoding-magic-comment nil)
