;; Stop creating files!
(setq make-backup-files nil)
(setq backup-inhibited t)
(setq auto-save-default nil)
(setq create-lockfiles nil)

(setq-default tab-width 2)
(setq-default indent-tabs-mode nil)
(setq inhibit-startup-message t)
(setq dired-use-ls-dired nil)
(setq rbenv-installation-dir "/usr/local")
(global-auto-revert-mode t)
(fset 'yes-or-no-p 'y-or-n-p)
(delete-selection-mode t)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(blink-cursor-mode t)
(show-paren-mode t)
(column-number-mode t)
(set-fringe-style 10)
(tooltip-mode -1)
(setq visible-bell t)
(setq ring-bell-function 'ignore)

;; flx can benefit significantly from garbage collection tuning.
(setq gc-cons-threshold 20000000)
