(sp-local-pair 'emacs-lisp-mode "'" nil :actions nil)
(sp-local-pair 'markdown-mode "'" nil :actions nil)
(sp-local-pair 'text-mode "'" nil :actions nil)
(sp-local-pair 'lisp-mode "'" nil :actions nil)
(sp-local-pair 'clojure-mode "'" nil :actions nil)
